---
- name: GRAB F5 FACTS
  hosts: all
  connection: local
  gather_facts: no


  tasks:

    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        provider: "{{provider}}"
        gather_subset:
          - "{{data_entity}}"

